server:
  port: 8888
  servlet:
    context-path: /springboot
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
      druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://39.96.161.245:3306/business
        username: lie
        password: Lie1998..
        max-active: 20
        max-wait: 6000
        min-idle: 1
        test-on-borrow: true
        test-on-return: true
mybatis:
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml