package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);

    /**
     * 根据用户id和商品id查询购物车
     * */

    Cart selectCartByUserIdAndProductId(@Param("userId") Integer userId,
                                        @Param("productId") Integer productId);

    /**
     * 查询用户的购物车信息
     * */
    List<Cart> selectCartByUserId(Integer userId);

    /**
     * 统计checked为0的商品
     * @param >0  说明没全选
     * */
    int isCheckedAll(Integer userId);

    /**
     * 删除购物车中某些商品
     * */
    int deleteByUseridAndProductIds(@Param("userId") Integer userId,
                                    @Param("productIdList") List<Integer> productIdList);

    /**
     * 操作购物车商品是否被选中
     * @param check 1:选中 0:未选中
     * */
    int selectOrUnselectProduct(@Param("userId") Integer userId,
                                @Param("productId") Integer productId,
                                @Param("check") Integer check);

    /**
     * 统计用户购物车中产品的数量
     * */

    int get_cart_product_count(Integer userId);

    /**
     * 根据用户id和被选中的查询
     * */
    List<Cart> findCartListByUserIdAndChecked(Integer userId);

    /**
     * 批量删除购物车商品
     * */
    int batchDelete(List<Cart> cartList);
}