package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import com.neuedu.pojo.Order;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);

    /**
     * 根据userid和orderno查询订单
     * */
    Order selectOrderByUserIdAndOrderNo(@Param("userId") Integer userId,
                                        @Param("orderNo") Long orderNo);

    List<Order> findOrderByUserId(Integer userId);

    Order selectOrderByOrderNo(Long orderNo);

    int updateOrderStatusAndPaymentTimeByOrderNo(@Param("order") Order order);



}