package com.neuedu.dao;

import com.neuedu.pojo.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    /**
     * 检验用户名是否存在
     * */
    int checkUsername(@Param("username") String username);

    /**
     * 根据用户名和密码查询用户信息
     * */
    User selectUserByUsernameAndPassword(@Param("username") String username,
                                         @Param("password") String password);

    /**
     * 检测邮箱是否存在
     * */
    int checkEmail(@Param("email") String email);

    /**
     * 根据用户名查询密保问题
     * */
    String selectQuestionByUsername(@Param("username") String username);


    /**
     * 根据用户名，密保问题，答案进行查询答案是否正确
     * */
    int selecByUsernameAndQuestionAndAnswer(@Param("username") String username,
                                            @Param("question") String question,
                                            @Param("answer") String answer);

    /**
     * 根据用户名修改密码
     * */
    int updatePasswordByUsername(@Param("username") String username,
                                 @Param("password") String passwordNew);


    /**
     * 登录状态下更新个人信息
     * */
    int updateUserByExistenceField(User user);



}